### ISSUE TITLE
installing auth_cas

### ISSUE THREAD

**Issue by ebremer** [oliverguenther/openproject-auth_cas#1]
I did an install of OP and it works fine.  I followed the directions in the auth_cas README but OP won't start with the following in the logs:

/opt/openproject-ce/vendor/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.10.0.pre.2/lib/bundler/source/git/git_proxy.rb:155:in `allowed_in_path': The git source https://github.com/opf/openproject-auth_plugins is not yet checked out. Please run`bundle install` before trying to start your application (Bundler::Git
Error)

What is the best way to resolve this issue?

**Comment by oliverguenther** [comment]
I see that this part is missing from the readme: As with any plugin installation, you need to run `bundle install` to actually install the gems specified in Gemfile.plugins.
