### ISSUE TITLE
Bundler could not find compatible versions for gem "omniauth":

### ISSUE THREAD

**Issue by michaeled30** [oliverguenther/openproject-auth_cas#2]
Hi,

I have this issue :

Fetching https://github.com/oliverguenther/openproject-auth_cas
Fetching https://github.com/finnlabs/omniauth-openid-connect.git
Fetching https://github.com/finnlabs/omniauth-openid_connect-providers.git
Fetching git://github.com/oliverguenther/omniauth.git
Fetching gem metadata from https://rubygems.org/........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies..........
Bundler could not find compatible versions for gem "omniauth":
  In Gemfile:
    omniauth

```
openproject-auth_cas was resolved to 0.1.0, which depends on
  omniauth-cas (>= 1.1.0, ~> 1.1) was resolved to 1.1.0, which depends on
    omniauth (~> 1.2.0)

omniauth-openid-connect was resolved to 0.2.0, which depends on
  omniauth (~> 1.1)

openproject-auth_plugins was resolved to 5.0.17, which depends on
  omniauth (~> 1.0)
```

**Comment by oliverguenther** [comment]
Hey @michaeled30, 

this should be fixed on dev with https://github.com/oliverguenther/openproject-auth_cas/commit/473d4146039cccf6ec05fc4c8939a7c52c3dbbc2.

**Comment by oliverguenther** [comment]
Hi @michaeled30,

I've relaxed the dependency in my own file and have suggested to do the same in our openid-connect plugin over at: 
https://github.com/finnlabs/omniauth-openid-connect/pull/2

That's all I can do here, so I'm closing this issue.

Best,
Oliver
