### ISSUE TITLE
Does it work on 10.0.2

### ISSUE THREAD

**Issue by dannymk** [oliverguenther/openproject-auth_cas#6]
I tried upgrading to 10.0.2 from 10.0.0 and the login link disappeared.  Is this plugin compatible with 10.0.2?

**Comment by dannymk** [comment]
https://community.openproject.com/topics/11243

**Comment by oliverguenther** [comment]
Hi @dannymk , yes unfortunately this plugin also uses the EE-only authentication plugins bridge that's been disabled with 10.0. You could manually register this plugin, bypassing the AuthPlugins registration. But that need some minor changes

Best,
Oliver
